# Generated by Django 5.1.7 on 2026-04-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discovery", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="badge_label",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
