# Generated by Django 5.1.7 on 2026-05-04 11:22

import discovery.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discovery", "0002_collection_badge_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="banner",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=discovery.models.banner_image_path
            ),
        ),
        migrations.AddField(
            model_name="collection",
            name="cover_image",
            field=models.ImageField(
                blank=True, null=True, upload_to=discovery.models.collection_image_path
            ),
        ),
        migrations.AlterField(
            model_name="banner",
            name="image_url",
            field=models.CharField(
                blank=True,
                help_text="Link ảnh ngoài (nếu không upload file)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="cover_image_url",
            field=models.CharField(
                blank=True,
                help_text="Link ảnh ngoài (nếu không upload file)",
                max_length=255,
                null=True,
            ),
        ),
    ]
