# Generated by Django 5.2.7 on 2025-11-26 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="Tiêu đề")),
                ("message", models.TextField(verbose_name="Nội dung")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("BOOKING", "Booking"),
                            ("RESTAURANT", "Restaurant"),
                            ("SYSTEM", "System"),
                        ],
                        default="SYSTEM",
                        max_length=50,
                        verbose_name="Loại thông báo",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Thời gian gửi"
                    ),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="Đã đọc")),
                (
                    "related_object_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("related_object_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người nhận",
                    ),
                ),
            ],
            options={
                "verbose_name": "Thông báo",
                "verbose_name_plural": "Thông báo",
                "db_table": "notifications",
                "ordering": ["-sent_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-sent_at"],
                        name="notificatio_user_id_f380a0_idx",
                    ),
                    models.Index(
                        fields=["user", "is_read"],
                        name="notificatio_user_id_a4dd5c_idx",
                    ),
                ],
            },
        ),
    ]
