# Generated by Django 5.1.7 on 2026-05-04 17:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_otpverification"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="last_district",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="last_latitude",
            field=models.DecimalField(
                blank=True, decimal_places=9, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="last_longitude",
            field=models.DecimalField(
                blank=True, decimal_places=9, max_digits=12, null=True
            ),
        ),
    ]
