# Generated by Django 5.2.7 on 2025-11-26 04:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("restaurants", "0002_alter_restaurantimage_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("booking_date", models.DateField()),
                ("number_of_guests", models.IntegerField()),
                ("special_request", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("CONFIRMED", "Confirmed"),
                            ("REJECTED", "Rejected"),
                            ("CANCELLED", "Cancelled"),
                            ("COMPLETED", "Completed"),
                            ("NO_SHOW", "No Show"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        limit_choices_to={"role": "CUSTOMER"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="restaurants.restaurant",
                    ),
                ),
                (
                    "time_slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="restaurants.timeslot",
                    ),
                ),
            ],
            options={
                "db_table": "bookings",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["customer", "status"],
                        name="bookings_custome_b789e2_idx",
                    ),
                    models.Index(
                        fields=["restaurant", "booking_date"],
                        name="bookings_restaur_3cc4da_idx",
                    ),
                    models.Index(
                        fields=["status", "booking_date"],
                        name="bookings_status_b2c90c_idx",
                    ),
                ],
            },
        ),
    ]
