# Generated by Django 5.1.7 on 2026-03-17 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0002_booking_deposit_amount_booking_is_deposit_paid"),
        ("promotions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="discount_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name="booking",
            name="voucher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bookings",
                to="promotions.voucher",
            ),
        ),
    ]
