# Generated by Django 5.1.7 on 2026-04-28 07:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0003_booking_discount_amount_booking_voucher"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="deposit_expires_at",
            field=models.DateTimeField(
                blank=True, help_text="Thời hạn thanh toán tiền cọc", null=True
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="rejection_reason",
            field=models.TextField(
                blank=True, help_text="Lý do từ chối đơn", null=True
            ),
        ),
    ]
