# Generated by Django 5.1.7 on 2026-05-04 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0004_booking_deposit_expires_at_booking_rejection_reason"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Chờ xác nhận"),
                    ("CONFIRMED", "Đã xác nhận"),
                    ("REJECTED", "Đã từ chối"),
                    ("CANCELLED", "Đã hủy"),
                    ("COMPLETED", "Hoàn thành"),
                    ("NO_SHOW", "Khách không đến"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
