# Generated by Django 5.1.7 on 2026-03-27 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("promotions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="voucher",
            name="points_cost",
            field=models.IntegerField(default=0),
        ),
    ]
