# Generated by Django 5.2.7 on 2025-11-17 08:51

import restaurants.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurants", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="restaurantimage",
            options={
                "ordering": ["display_order", "-created_at"],
                "verbose_name": "Restaurant Image",
                "verbose_name_plural": "Restaurant Images",
            },
        ),
        migrations.RemoveField(
            model_name="menuitem",
            name="image_url",
        ),
        migrations.RemoveField(
            model_name="restaurantimage",
            name="image_url",
        ),
        migrations.AddField(
            model_name="menuitem",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Upload ảnh món ăn (JPG, PNG)",
                null=True,
                upload_to=restaurants.models.menu_item_image_upload_path,
            ),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="restaurantimage",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="restaurantimage",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Upload ảnh nhà hàng (JPG, PNG)",
                null=True,
                upload_to=restaurants.models.restaurant_image_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
