# Generated by Django 5.1.7 on 2026-03-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurants", "0002_alter_restaurantimage_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="cuisine_type",
            field=models.CharField(
                blank=True,
                help_text="VD: Món Việt, Nhật Bản, Ý, BBQ...",
                max_length=100,
                null=True,
            ),
        ),
    ]
