# Generated by Django 5.1.7 on 2026-04-11 01:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurants", "0004_favoriterestaurant"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="price_range",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BUDGET", "Bình dân (dưới 100k/người)"),
                    ("MEDIUM", "Trung bình (100k–300k/người)"),
                    ("PREMIUM", "Cao cấp (trên 300k/người)"),
                ],
                help_text="Mức giá trung bình mỗi người",
                max_length=10,
                null=True,
            ),
        ),
    ]
