# Generated by Django 5.1.7 on 2026-04-23 07:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("restaurants", "0008_rename_indexes"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="timeslot",
            name="time_slots_start_before_end",
        ),
        migrations.RemoveField(
            model_name="restaurant",
            name="slot_duration",
        ),
        migrations.RemoveField(
            model_name="timeslot",
            name="end_time",
        ),
    ]
