# Generated by Django 5.1.7 on 2026-04-28 07:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurants", "0010_restaurantreport"),
    ]

    operations = [
        migrations.AddField(
            model_name="timeslot",
            name="max_guests_per_booking",
            field=models.IntegerField(
                default=20,
                help_text="Số khách tối đa cho một đơn đặt bàn",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
    ]
