# Generated by Django 5.1.7 on 2026-04-28 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurants", "0011_timeslot_max_guests_per_booking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="price_range",
            field=models.CharField(
                blank=True,
                help_text="Mức giá trung bình mỗi người (số nguyên)",
                max_length=20,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="BlockedDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        help_text="VD: Nghỉ lễ, Bảo trì, Tiệc riêng...",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocked_dates",
                        to="restaurants.restaurant",
                    ),
                ),
            ],
            options={
                "db_table": "blocked_dates",
                "ordering": ["date"],
                "unique_together": {("restaurant", "date")},
            },
        ),
    ]
