# Generated by Django 5.1.7 on 2026-04-28 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurants", "0012_alter_restaurant_price_range_blockeddate"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeSlotOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "max_bookings",
                    models.IntegerField(
                        blank=True,
                        help_text="Sức chứa mới cho ngày này (Để trống nếu giữ nguyên)",
                        null=True,
                    ),
                ),
                ("max_guests_per_booking", models.IntegerField(blank=True, null=True)),
                (
                    "is_closed",
                    models.BooleanField(
                        default=False,
                        help_text="Đánh dấu nếu muốn đóng cửa khung giờ/ngày này",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        help_text="Lý do: Lễ, Tết, Bảo trì...",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_slot_overrides",
                        to="restaurants.restaurant",
                    ),
                ),
                (
                    "time_slot",
                    models.ForeignKey(
                        blank=True,
                        help_text="Để trống nếu áp dụng cho tất cả khung giờ trong ngày",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="overrides",
                        to="restaurants.timeslot",
                    ),
                ),
            ],
            options={
                "db_table": "time_slot_overrides",
                "ordering": ["date", "time_slot__start_time"],
                "unique_together": {("restaurant", "date", "time_slot")},
            },
        ),
        migrations.DeleteModel(
            name="BlockedDate",
        ),
    ]
