# Generated by Django 5.1.7 on 2026-05-02 15:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("restaurants", "0013_timeslotoverride_delete_blockeddate"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="location",
            name="locations_provinc_4fd08f_idx",
        ),
        migrations.RemoveIndex(
            model_name="location",
            name="locations_distric_50aa45_idx",
        ),
        migrations.RemoveIndex(
            model_name="location",
            name="locations_ward_co_f919aa_idx",
        ),
        migrations.RemoveField(
            model_name="location",
            name="district_code",
        ),
        migrations.RemoveField(
            model_name="location",
            name="province_code",
        ),
        migrations.RemoveField(
            model_name="location",
            name="ward_code",
        ),
    ]
