# Generated by Django 5.1.7 on 2026-05-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurants", "0014_remove_location_locations_provinc_4fd08f_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="district_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="province_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="ward_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="price_range",
            field=models.CharField(
                blank=True,
                help_text="Giá trung bình mỗi người - lưu dạng SỐ NGUYÊN VND, vd: 80000, 150000, 350000",
                max_length=20,
                null=True,
            ),
        ),
    ]
