# Generated by Django 5.1.7 on 2026-05-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurants", "0017_restaurantviewhistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=9, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=9, max_digits=12, null=True
            ),
        ),
    ]
