# Generated by Django 5.1.7 on 2026-03-17 14:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="frozen_balance",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
