# Generated by Django 5.1.7 on 2026-04-28 07:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0002_wallet_frozen_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="depositpolicy",
            name="deposit_per_guest",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Tiền cọc tính trên mỗi đầu người",
                max_digits=12,
            ),
        ),
    ]
