# Generated by Django 5.1.7 on 2026-04-28 08:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0003_depositpolicy_deposit_per_guest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="depositpolicy",
            name="is_required",
            field=models.BooleanField(default=True),
        ),
    ]
