# Generated by Django 5.1.7 on 2026-04-28 09:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0002_reviewimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="is_read_by_partner",
            field=models.BooleanField(default=False),
        ),
    ]
